# Python dictionary containing the keywords and the corresponding value currently available in the change expression mode
cfe_dict = {
  "Expression": 
  [
    "angry",
    "astonished",
    "cry",
    "disgusted",
    "fearful", 
    "happy", 
    "neutral",
    "pathetic",
    "sad",
    "surprised", 
    "suspicious", 
  ],
  "Eyes": 
  [
    "closed", 
    "open", 
    "wink_left", 
    "wink_right", 
  ],
  "Gaze": 
  [
    "left", 
    "right",
    "up",
    "down", 
  ]
}
