# Python file containing the list of all the possible value for the keywords: Country, Gender, Emotion, Mouth, Nose
country_list = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina",
    "Burundi",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Cape Verde",
    "Central African Rep",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Ivory Coast",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea North",
    "Korea South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Macedonia",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russian Federation",
    "Rwanda",
    "St Lucia",
    "Saint Vincent",
    "Samoa",
    "San Marino",
    "Sao Tome & Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Swaziland",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad & Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
]

emotion_list = [
    "affectionate",
    "agitated",
    "amused",
    "angry",
    "annoyed",
    "anxious",
    "astonished",
    "astounded",
    "calm",
    "caring",
    "comforted",
    "compassionate",
    "confused",
    "content",
    "delighted",
    "depressed",
    "despairing",
    "devoted",
    "disgusted",
    "dumbfounded",
    "elated",
    "empathetic",
    "enamored",
    "enraged",
    "excited",
    "fearful",
    "furious",
    "grateful",
    "grinning",
    "gloomy",
    "happy",
    "heartbroken",
    "hopeless",
    "indignant",
    "irritated",
    "isolated",
    "joyful",
    "lonely",
    "lost",
    "loved",
    "melancholic",
    "miserable",
    "nauseated",
    "nervous",
    "offended",
    "panicked",
    "passionate",
    "perplexed",
    "pleased",
    "rejected",
    "relieved",
    "repulsed",
    "resentful",
    "sad",
    "scared",
    "shocked",
    "speechless",
    "stressed",
    "surprised",
    "sympathetic",
    "tender",
    "terrified",
    "tense",
    "warm",
    "worried"
];

gender_list = [
    "female",
    "male",
    "none"
]

mouth_list = [
    "arguing",
    "babbling",
    "beaming",
    "bickering",
    "biting",
    "breathing",
    "browsing",
    "calm",
    "caring",
    "chattering",
    "chewing",
    "chuckling",
    "closed",
    "confused",
    "content",
    "crying",
    "debating",
    "discussing",
    "distressed",
    "drowsy",
    "exhausted",
    "frowning",
    "gasping",
    "gargling",
    "giggling",
    "gnawing",
    "gossiping",
    "grinning",
    "grimacing",
    "groaning",
    "hissing",
    "intrigued",
    "jabbering",
    "laughing",
    "licking",
    "lisping",
    "mouthing",
    "moaning",
    "munching",
    "mumbling",
    "nibbling",
    "open",
    "pouting",
    "prattling",
    "relaxed",
    "screaming",
    "serene",
    "shouting",
    "sighing",
    "singing",
    "sleepy",
    "slurring",
    "smiling",
    "smirking",
    "slobbering",
    "stammering",
    "stressed",
    "stuttering",
    "sucking",
    "surprised",
    "talking",
    "tense",
    "tired",
    "weary",
    "whimpering",
    "whispering",
    "whistling",
]

nose_list = [
    "big",
    "bumpy",
    "button",
    "crooked",
    "cute",
    "delicate",
    "elegant",
    "graceful",
    "hooked",
    "large",
    "long",
    "perfect",
    "petite",
    "prominent",
    "refined",
    "shapely",
    "straight",
    "wide"
]